#!/usr/bin/env python
from SocketServer import StreamRequestHandler, TCPServer
import subprocess
import threading
import time
import sys

LLD_NAME = 'SD1_IO'

def sim_format(lld, data):
  return '%s\t%s\n' % (lld , data.encode('hex'))

class SIMIO(StreamRequestHandler):
  def handle(self):
    print '[SIMIO] CONNECT'
    threading.Thread(target=self.read_thread).start()
    while True:
      self.write_line()

  def write_line(self):
    data = sys.stdin.readline()
    print '[%s] -> %r' % (LLD_NAME, data)
    msg = sim_format(LLD_NAME, data)
    self.wfile.write(msg)

  def read_thread(self):
    while True:
      line = self.rfile.readline()
      header, code = line.strip().split('\t', 1)
      data = code.decode('hex')
      sys.stdout.write('[%s] <- %r\n' % (header, data))

# prevent bind errors on relaunch
TCPServer.allow_reuse_address = True

# listen for simio connections
simio = TCPServer(('localhost', 27000), SIMIO)
simio_thread = threading.Thread(target=simio.handle_request)
simio_thread.start()

# spawn the unit test
subprocess.check_call(['./ch'])
