#!/usr/bin/env python
from SocketServer import StreamRequestHandler, TCPServer
import subprocess
import threading
import time
import sys

BUTTON_DELAY = 1

class PAL(StreamRequestHandler):
  def handle(self):
    print '[PAL] CONNECT'
    for line in self.rfile:
      sys.stdout.write('[PAL] <- %s' % line)

class EXT(StreamRequestHandler):
  channel = '\x00'

  def handle(self):
    print '[EXT] CONNECT'
    while True:
      print '[EXT] -> %s' % repr(self.channel)
      self.wfile.write(self.channel)
      time.sleep(BUTTON_DELAY)

# prevent bind errors on relaunch
TCPServer.allow_reuse_address = True

# listen for PAL connections
pal = TCPServer(('localhost', 27000), PAL)
pal_th = threading.Thread(target=pal.handle_request)
pal_th.setDaemon(True)
pal_th.start()

# listen for EXT connections
ext = TCPServer(('localhost', 27020), EXT)
ext_th = threading.Thread(target=ext.handle_request)
ext_th.setDaemon(True)
ext_th.start()

# spawn the unit test
subprocess.check_call(['./ch'])
